<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-CYPVPEJ4PK"></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-CYPVPEJ4PK');

  </script>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <title>Learning (not) to Handle Exceptions | Python For The Lab</title>

  <meta name="tags" content="Exceptions, Errors, Try, Except, Catch, Handling, ">
  <meta name="description" content="Learn how to deal with exceptions in Python">
  <meta name="author" content="Aquiles Carattino">
  <link rel="canonical" href="https://pythonforthelab.com/blog/learning-not-to-handle-exceptions">

  <!-- Open Graph / Facebook -->
  <meta property="og:site_name" content="Python for the Lab">
  <meta property="og:type" content="article">
  <meta property="og:url" content="https://pythonforthelab.com/blog/learning-not-to-handle-exceptions">
  <meta property="og:title" content="Learning (not) to Handle Exceptions">
  <meta property="og:description" content="Learn how to deal with exceptions in Python">
  <meta property="og:image" content="/images/cody-davis-253928-unsplash_linkedin.width-800.jpg">

  <!-- Twitter -->
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:url" content="https://pythonforthelab.com/blog/learning-not-to-handle-exceptions">
  <meta property="twitter:title" content="Learning (not) to Handle Exceptions">
  <meta property="twitter:description" content="Learn how to deal with exceptions in Python">
  <meta property="twitter:image" content="/images/cody-davis-253928-unsplash_linkedin.width-800.jpg">
  <meta name="twitter:creator" content="@aquicarattino">

  <link rel="apple-touch-icon" sizes="57x57"
        href="https://pythonforthelab.com/theme/css/favicon/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60"
        href="https://pythonforthelab.com/theme/css/favicon/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72"
        href="https://pythonforthelab.com/theme/css/favicon/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76"
        href="https://pythonforthelab.com/theme/css/favicon/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114"
        href="https://pythonforthelab.com/theme/css/favicon/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120"
        href="https://pythonforthelab.com/theme/css/favicon/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144"
        href="https://pythonforthelab.com/theme/css/favicon/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152"
        href="https://pythonforthelab.com/theme/css/favicon/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180"
        href="https://pythonforthelab.com/theme/css/favicon/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"
        href="https://pythonforthelab.com/theme/css/favicon/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32"
        href="https://pythonforthelab.com/theme/css/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96"
        href="https://pythonforthelab.com/theme/css/favicon/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16"
        href="https://pythonforthelab.com/theme/css/favicon/favicon-16x16.png">
  <link rel="manifest" href="https://pythonforthelab.com/theme/css/favicon/manifest.json"/>
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="https://pythonforthelab.com/theme/css/favicon/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
  <link
      href="https://fonts.googleapis.com/css2?family=Markazi+Text:wght@400;700&family=Playfair+Display:wght@400;700&family=Poppins:wght@300;400;700&display=swap"
      rel="stylesheet">

  <link rel="stylesheet" href="https://files.stork-search.net/basic.css"/>
  <link rel="stylesheet" href="https://pythonforthelab.com/theme/css/tw_style.css">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="https://https://pythonforthelab.com/feed.rss">	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script type="text/javascript" src="https://pythonforthelab.com/theme/js/jquery-migrate-1.2.1.js"></script>

	<script src="https://pythonforthelab.com/theme/js/functions.js"></script>  <link rel="stylesheet" href="https://pythonforthelab.com/theme/css/prism.css"/>
</head>

<body class="text-gray-800">
  <header class="relative bg-gray-800 md:h-80 lg:flex h-64">
    <div class="lg:flex-col lg:lg:w-[880px] lg:ml-16">
      <nav class="lg:pr-8 w-full lg:pt-4">
        <div class="flex p-3 items-center justify-between">
          <a class="flex-none" href="https://pythonforthelab.com">
            <img id="site-logo" class="h-12"
                 src="https://pythonforthelab.com/theme/css/images/logo-red.svg"/>
          </a>
          <div id="menu_sm"
               class="pr-0 pl-4 grow hidden lg:block">
<ul
        class="w-full font-semibold text-3xl lg:flex lg:pl-16 lg:text-white md:text-base md:font-medium z-50">
    <li class="nav-item md:grow align-middle ">
        <a href="https://pythonforthelab.com/blog"
           class="md:pt-6 md:pb-2 hover:border-b-2 hover:border-red-400">
            <span class="">Blog</span>
        </a>
    </li>
    <li class="nav-item md:grow align-middle ">
        <a href="https://pythonforthelab.com/courses"
           class="md:pt-6 md:pb-2 hover:border-b-2 hover:border-red-400">
            <span class="">Courses</span>
        </a>
    </li>
    <li class="nav-item md:grow align-middle ">
        <a href="https://pythonforthelab.com/hire-me"
           class="md:pt-6 md:pb-2 hover:border-b-2 hover:border-red-400">
            <span class="">Hire Me</span>
        </a>
    </li>
    <li class="nav-item md:grow align-middle ">
        <a href="https://pythonforthelab.com/books"
           class="md:pt-6 md:pb-2 hover:border-b-2 hover:border-red-400">
            <span class="">Books</span>
        </a>
    </li>
    <li class="nav-item md:grow align-middle ">
        <a href="https://pythonforthelab.com/about"
           class="md:pt-6 md:pb-2 hover:border-b-2 hover:border-red-400">
            <span class="">About</span>
        </a>
    </li>
    <li class="nav-item md:grow align-middle ">
        <a href="https://github.com/PFTL/pftl_discussions/discussions"
           class="md:pt-6 md:pb-2 hover:border-b-2 hover:border-red-400">
            <span class="">Forum</span>
        </a>
    </li>
    <li class="pt-4 md:hidden">
        <form action="#" class="w-full pr-8">
            <label for="search" class="relative block">
                <img class="absolute w-4 h-4 top-1/2 -translate-y-1/2 left-3"
                     src="https://pythonforthelab.com/theme/css/images/search.svg">
                <input id="search" data-stork="sitesearch" type="text"
                       class="text-base placeholder-gray-500 pl-10 py-4 w-full shadow-sm ring-1 ring-inset ring-gray-300 focus:border-2 focus:border-red-500 focus:ring-red-500"
                       placeholder="Type to Search">
            </label>
        </form>
        <div data-stork="sitesearch-output"></div>
    </li>
</ul>          </div>
          <div class="">
            <button id="menu-button" class="z-50 border-1 border-red-500 lg:hidden">
              <img id="hamburger" src="https://pythonforthelab.com/theme/css/images/hamburger.svg"
                   class="h-8 w-8"/>
            </button>
          </div>
        </div>
        <div id="menu"
             class="pr-0 pb-8 mx-0 pt-8 pl-12 basis-full grow bg-white z-30 min-w-full hidden drop-shadow-lg border-b-8 border-b-red-700">
<ul
        class="w-full font-semibold text-3xl md:grid md:grid-cols-6 md:px-16 md:text-base md:font-medium">
    <li class="nav-item align-middle md:h-16 md:pl-8  md:shadow-xl md:hover:shadow-2xl md:active:shadow-none">
        <a href="https://pythonforthelab.com/blog"
           class="before:content-blogIcon
            before:inline-block before:align-middle before:h-6 before:w-6 md:py-6 md:pr-12
            before:md:h-8 before:md:w-8">
            <span class="">Blog</span>
        </a>
    </li>
    <li class="nav-item align-middle md:h-16 md:pl-8  md:shadow-xl md:hover:shadow-2xl md:active:shadow-none">
        <a href="https://pythonforthelab.com/courses"
           class="before:content-coursesIcon md:w-full
            before:inline-block before:align-middle before:h-6 before:w-6 md:py-6 md:pr-12
            before:md:h-8 before:md:w-8">
            <span class="">Courses</span>
        </a>
    </li>
    <li class="nav-item align-middle md:h-16 md:pl-8  md:shadow-xl md:hover:shadow-2xl md:active:shadow-none">
        <a href="https://pythonforthelab.com/hire-me"
           class="before:content-hireIcon
            before:inline-block before:align-middle before:h-6 before:w-6 md:py-6 md:pr-12
            before:md:h-8 before:md:w-8">
            <span class="">Hire Me</span>
        </a>
    </li>
    <li class="nav-item align-middle md:h-16 md:pl-8  md:shadow-xl md:hover:shadow-2xl md:active:shadow-none">
        <a href="https://pythonforthelab.com/books"
           class="before:content-booksIcon
            before:inline-block before:align-middle before:h-6 before:w-6 md:py-6 md:pr-12
            before:md:h-8 before:md:w-8">
            <span class="">Books</span>
        </a>
    </li>
    <li class="nav-item align-middle md:h-16 md:pl-8  md:shadow-xl md:hover:shadow-2xl md:active:shadow-none">
        <a href="https://pythonforthelab.com/about"
           class="before:content-aboutIcon
            before:inline-block before:align-middle before:h-6 before:w-6 md:py-6 md:pr-12
            before:md:h-8 before:md:w-8">
            <span class="">About</span>
        </a>
    </li>
    <li class="nav-item align-middle md:h-16 md:pl-8  md:shadow-xl md:hover:shadow-2xl md:active:shadow-none">
        <a href="https://github.com/PFTL/pftl_discussions/discussions"
           class="before:content-forumIcon
            before:inline-block before:align-middle before:h-6 before:w-6 md:py-6 md:pr-12
            before:md:h-8 before:md:w-8">
            <span class="">Forum</span>
        </a>
    </li>
    <li class="pt-4 md:hidden">
        <form action="#" class="w-full pr-8">
            <label for="search" class="relative block">
                <img class="absolute w-4 h-4 top-1/2 -translate-y-1/2 left-3"
                     src="https://pythonforthelab.com/theme/css/images/search.svg">
                <input id="search" data-stork="sitesearch" type="text"
                       class="text-base placeholder-gray-500 pl-10 py-4 w-full shadow-sm ring-1 ring-inset ring-gray-300 focus:border-2 focus:border-red-500 focus:ring-red-500"
                       placeholder="Type to Search">
            </label>
        </form>
        <div data-stork="sitesearch-output"></div>
    </li>
</ul>        </div>
      </nav>
      <div class="md:flex text-gray-200 lg:min-w-full lg:pt-4 pb-8">
      </div>
    </div>
    <div class="hidden lg:block lg:w-72 ml-1 pl-2 mr-2 pt-4 w-72">
      <div class="mb-8 shadow-2xl">
        <form action="#" class="w-full pr-8 pt-4 text-xs">
          <label for="search" class="relative block">
            <img class="absolute w-4 h-4 top-1/2 -translate-y-1/2 left-3"
                 src="https://pythonforthelab.com/theme/css/images/search.svg">
            <input id="search" data-stork="sitesearch" type="text"
                   class="text-gray-800 pl-10 bg-white py-2 placeholder-gray-500 w-full border border-gray-600"
                   placeholder="Type to Search">
          </label>
        </form>
        <div data-stork="sitesearch-output"></div>
      </div>
      <div class="py-2 shadow-2xl">
        <div class="text-gray-300">
          <span class="font-semibold text-sm">Get all the information directly to your inbox.</span>
        </div>
        <div id="mc_embed_signup" class="">
          <form
              action="https://pythonforthelab.us21.list-manage.com/subscribe/post?u=f0d9bfa6188cdcc67890a07f6&amp;id=8a0ca536e8&amp;f_id=00dfebe6f0"
              method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
              class="validate my-3 md:max-w-lg"
              target="_self" novalidate="">
            <div class="field-wp">
              <input type="email" name="EMAIL" placeholder="Your E-Mail" id="mce-EMAIL" required=""
                     value=""
                     class="required email bg-white ring-red-500 p-2 w-full md:max-w-2/3">
            </div>
            <div id="mce-responses" class="clear foot">
              <div class="response" id="mce-error-response" style="display: none;"></div>
              <div class="response" id="mce-success-response" style="display: none;"></div>
            </div>
            <div style="position: absolute; left: -5000px;" aria-hidden="true">
              /* real people should not fill this in and expect good things - do not remove this or risk
              form
              bot
              signups */
              <input type="text" name="b_f0d9bfa6188cdcc67890a07f6_8a0ca536e8" tabindex="-1" value="">
            </div>
            <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"
                   class="bg-emerald-500 hover:scale-105 focus:bg-emerald-300 text-white p-4 mt-2 w-full md:max-w-2/3">
          </form>
          <span class="text-gray-400 text-xs">Unsubscribe any time.</span>
        </div>
      </div>
    </div>
  </header>

  <div class="lg:mx-auto lg:flex lg:ml-16">

    <div id="col-left" class="md:content-stretch lg:w-[880px]">
      <div class="relative text-gray-800 mx-2 z-40">
        <div class="md:-mt-32 lg:-mt-56 -mt-36 lg:mb-8">
          <img src="/images/cody-davis-253928-unsplash_linkedin.width-800.jpg" alt="Learning (not) to Handle Exceptions" class="shadow-md lg:shadow-lg"/>
        </div>
        <h1 class="font-serif font-extrabold text-4xl leading-tight pb-2">Learning (not) to Handle Exceptions</h1>
        <div class="font-sans font-bold text-xl">Learn how to deal with exceptions in Python</div>
        <div class="text-sm text-gray-400">
          <span
              class="inline-block before:inline-block before:mx-1 before:align-middle before:h-4 before:w-4 before:content-profile mr-1 pr-1 py-1">Aquiles Carattino</span>
          <span
              class="inline-block before:inline-block before:mx-1 before:align-middle before:h-4 before:w-4 before:content-calendar mr-1 pr-1 py-1">2018-06-04</span>
          <span
              class="inline-block before:inline-block before:mx-1 before:align-middle before:h-4 before:w-4 before:content-tag mr-1 pr-1 py-1">
              <span class="bg-gray-300 rounded text-white px-0.5 mr-0.5 ">Exceptions</span>
              <span class="bg-gray-300 rounded text-white px-0.5 mr-0.5 ">Errors</span>
              <span class="bg-gray-300 rounded text-white px-0.5 mr-0.5 ">Try</span>
              <span class="bg-gray-300 rounded text-white px-0.5 mr-0.5 ">Except</span>
              <span class="bg-gray-300 rounded text-white px-0.5 mr-0.5 ">Catch</span>
              <span class="bg-gray-300 rounded text-white px-0.5 mr-0.5 ">Handling</span>
        </span>
        </div>
      </div>

      <div class="article-content mt-4 mx-2">
        <main>
          <p>When you develop code, it is almost impossible not to run into an
error. Some problems are going to arise as soon as you start your
program, for example, if you forgot to close a parenthesis, or forgot
the <code>:</code> after an if-statement. However, errors at runtime are also
very frequent and harder to deal with. In this article, you are going
to learn how to handle exceptions, i.e. how to avoid program crashes
when you can anticipate that an error may appear.</p>
<p>We are going to cover from the basics of error handling to defining your
own exceptions. You will learn why sometimes it is better not to catch
exceptions and how to develop a pattern that can be useful for future
users of your code. Exceptions are a crucial part of any code, and
dealing with them elegantly can improve a lot the value of your code.</p>
<p>All the code of this article is <a href="https://github.com/PFTL/website/tree/master/example_code/12_exceptions">available on Github</a>.</p>
<h2>Try ... Except</h2>
<p>Imagine that you are reading data from a file. You can simply write
something like this:</p>
<pre><code class="language-python">f = open('my_file.dat')
data = f.readfile()
print('Data loaded')
</code></pre>
<p>If you run the code, you will see a message like the following:</p>
<pre><code class="language-bash">FileNotFoundError: [Errno 2] No such file or directory: 'my_file.dat'
</code></pre>
<p>When an error is raised, the code that follows will not be executed.
That is why you don't see the statement <code>Data loaded</code> on the console.
This is a somewhat innocent problem but imagine that you are
communicating with a device. If there is an error in your program, you
won't have the chance to close the communication with the device, or you
won't be able to close a shutter to prevent damages to the detectors,
etc.</p>
<p>Dealing with this kind of errors is normally done within a <code>try</code> /
<code>except</code> block. This means that if there is an error inside the <code>try</code>,
the block <code>except</code> will be executed. In the example above, we can do the
following:</p>
<pre><code class="language-python">try:
    f = open('my_file.dat')
    f.readfile()
    print('Loaded data')
except:
    print('Data not loaded')
</code></pre>
<p>If you run the code, you will see a nice message being printed to screen
saying <code>Data not loaded</code>. This is great! Now our program is not crashing
and we can close the shutter, or stop the communication with our device.
However, we don't know the reason why the data was not loaded.</p>
<p>Before continuing, create an empty file called <strong>my_file.dat</strong>, and run
the script again. You will see that data is not being loaded, regardless
whether the file exists or not. With this trivial example, you are
seeing the risks around unspecific <code>except</code> blocks. If we make a simpler
script:</p>
<pre><code class="language-python">f = open('my_file.dat')
f.readfile()
print('Loaded data')
</code></pre>
<p>The output will be:</p>
<pre><code class="language-bash">AttributeError: '_io.TextIOWrapper' object has no attribute 'readfile'
</code></pre>
<p>Which is telling us that the problem is the method that we tried to use,
<code>readfile</code> doesn't exist. When you use a plain <code>try/except</code> block, you
are sure you are handling all possible exceptions, but you have no way
of knowing what actually went wrong. In simple cases like the one above,
you have only two lines of code to explore. However, if you are building
a package or a function, some errors will propagate downstream, and you
don't know how they are going to affect the rest of the program.</p>
<p>For you to have an idea of the importance of correct handling of errors,
I will tell you what I have witnessed using a program that ships with a
very sophisticated lab instrument. The program that controls the <a href="https://www.malvernpanalytical.com/en/products/product-range/nanosight-range">Nano
Sight</a>
has a very nice user interface. However, when you are saving data, if
the filename you choose has a dot in it, the data will not be saved.
Sadly, the data will also be lost and the user will never know that the
problem was having a simple <code>.</code> in the filename.</p>
<p>Handling all possible errors in a graceful way is very complicated and
sometimes almost impossible. However, you can see that even the software
that ships with very expensive instruments (in this case I mean
instruments with a price tag similar to a small apartment), also has to
deal with all kinds of exceptions, and not always in the most
user-friendly way.</p>
<h2>Catching Specific Exceptions</h2>
<p>The proper way of handling exceptions in Python is to specify what
exception are we expecting. In this way, we know that if the problem is
that the file doesn't exist, we can create it, while if the problem is
of a different nature, it will be raised and displayed to the user. We
can alter the above examples like this:</p>
<pre><code class="language-python">try:
    file = open('my_file.dat')
    data = file.readfile()
    print('Data Loaded')
except FileNotFoundError:
    print('This file doesn\'t exist')
</code></pre>
<p>If you run the script, and the file <strong>my_file.dat</strong> doesn't exist, it
will print to screen that the file doesn't exist and the program will
keep running. However, if the file does exist, you will see the
exception with <code>readfile</code>. Of course, you are not limited to printing a
message when an exception happens. In the case of the non-existing file,
it is easy to create one:</p>
<pre><code class="language-python">try:
    file = open('my_file.dat')
    data = file.readfile()
    print('Data Loaded')
except FileNotFoundError:
    file = open('my_file.dat', 'w')
    print('File created')
file.close()
</code></pre>
<p>If you run the script once, you will see that the file is being created.
If you run the script a second time, you will see the exception with the
<code>readfile</code> method. Imagine that you don't specify which exception you
are catching, and you have the following code, what will happen when you
run it?:</p>
<pre><code class="language-python">try:
    file = open('my_file.dat')
    data = file.readfile()
    print('Data Loaded')
except:
    file = open('my_file.dat', 'w')
    print('File created')
</code></pre>
<p>If you look carefully, you will realize that even if the file
<strong>my_file.dat</strong> exists, an exception is going to be raised because of
the <code>readfile</code> method. Then the <code>except</code> block is going to be executed.
In this block, the program is going to create a new <strong>my_file.dat</strong>,
even if it already existed, and therefore you are going to lose the
information stored in it.</p>
<h2>Re-raising Exceptions</h2>
<p>A very common scenario is that when an exception appears, you want to do
something but then raise the same exception. This is a very common case
when writing to a database or to different files. Imagine the case where
you are storing information in two files, in the first one you store
spectra and in the second one the temperature at which you acquire each
one. You first save the spectra and then the temperature, and you know
that each line on one file corresponds to one file on the second file.</p>
<p>Normally, you save first a spectrum and then you save the temperature.
However, once in a while, when you try to read from the instrument, it
crashes and the temperature is not recorded. If you don't save the
temperature, you will have an inconsistency in your data, because a line
is missing. At the same time, you don't want the experiment to keep
going, because the instrument is frozen. Therefore, you can do the
following:</p>
<pre><code class="language-python">[data already saved]

try:
    temp = instrument.readtemp()
except:
    remove_last_line(data_file)
    raise
save_temperature(temp)
</code></pre>
<p>What you can see here is that we try to read the temperature and if
anything happens, we will catch it. We remove the last line from our
data file, and then we just call <code>raise</code>. This command will simply
re-raise anything that was caught by the <code>except</code>. With this strategy,
we are sure that we have consistent data, that the program will not keep
running and that the user will see all the proper information regarding
what went wrong.</p>
<h2>Exceptions in Exceptions</h2>
<p>Imagine that the code is part of a larger function, responsible for
opening a file, loading its contents or creating a new file in case the
specified filename doesn't exist. The script will look the same as
earlier, with the difference that the filename is going to be a
variable:</p>
<pre><code class="language-python">try:
    file = open(filename)
    data = file.readfile()
except FileNotFoundError:
    file = open(filename, 'w')
</code></pre>
<p>To run the code above, the only thing you have to do is to specify the
filename before, for instance:</p>
<pre><code class="language-python">filename = 'my_data.dat'
try:
    [...]
</code></pre>
<p>If you run this code, you will notice that it behaves exactly as
expected. However, if you specify an empty filename:</p>
<pre><code class="language-python">filename = ''
try:
    [...]
</code></pre>
<p>You will see a much longer error printed to screen, with one important
line:</p>
<pre><code class="language-bash">During handling of the above exception, another exception occurred:
</code></pre>
<p>If you look carefully at the error, you will see that it outputs
information regarding that an error occurred while the code was already
handling another error. This is, unfortunately, a common situation,
especially when dealing with user input. The way around it would be to
nest another try/except block or to verify the integrity of the inputs
before calling <code>open</code>.</p>
<h2>Several Exceptions</h2>
<p>So far we have been dealing with only one possible exception,
<code>FileNotFoundError</code>. However, we know that the code will raise two
different exceptions, the second one being an <code>AttributeError</code>. If you
are not sure about which errors can be raised, you can generate them on
purpose. For instance, if you run this code:</p>
<pre><code class="language-python">file = open('my_data.dat', 'a')
file.readfile()
</code></pre>
<p>You will get the following message:</p>
<pre><code class="language-bash">AttributeError: '_io.TextIOWrapper' object has no attribute 'readfile'
</code></pre>
<p>The first string is the type of exception, <code>AttributeError</code>, while the
second part is the message. The same exception can have different
messages, which describe better what has happened. What we want is to
catch the <code>AttributeError</code>, but also we want to catch the
<code>FileNotFound</code>. Therefore, our code would look like this:</p>
<pre><code class="language-python">filename = 'my_data.dat'

try:
    file = open(filename)
    data = file.readfile()
except FileNotFoundError:
    file = open(filename, 'w')
    print('Created file')
except AttributeError:
    print('Attribute Error')
</code></pre>
<p>Now you are dealing with several exceptions. Remember that when an
exception is raised within the <code>try</code> block, the rest of the code will
not be executed, and Python will go through the different <code>except</code>
blocks. Therefore, only one exception is raised at a time. In the case
where the file doesn't exist, the code will deal only with the
<code>FileNotFoundError</code>.</p>
<p>Of course, you can also add a final exception to catch all other
possible errors in the program, like this:</p>
<pre><code class="language-python">filename = 'my_data.dat'

try:
    file = open(filename)
    data = file.read()
    important_data = data[0]
except FileNotFoundError:
    file = open(filename, 'w')
    print('Created file')
except AttributeError:
    print('Attribute Error')
except:
    print('Unhandled exception')
</code></pre>
<p>In this case, if the file exists but it is empty, we are going to have a
problem trying to access <code>data[0]</code>. We are not prepared for that
exception and therefore we are going to print a message saying
<em>Unhandled exception</em>. It would be, however, more interesting to let the
user know what exception was actually raised. We can do the following:</p>
<pre><code class="language-python">filename = 'my_data.dat'

try:
    file = open(filename)
    data = file.read()
    important_data = data[0]
except Exception as e:
    print('Unhandled exception')
    print(e)
</code></pre>
<p>Which will output the following message:</p>
<pre><code class="language-bash">Unhandled exception
string index out of range
</code></pre>
<p>The exception also has a <code>type</code>, which you can use. For example:</p>
<pre><code class="language-python">filename = 'my_data.dat'

try:
    file = open(filename)
    data = file.read()
    important_data = data[0]
except Exception as e:
    print('Unhandled exception')
    if isinstance(e, IndexError):
        print(e)
        data = 'Information'
        important_data = data[0]

print(important_data)
</code></pre>
<p>Which will print the first letter of <code>Information</code>, i.e. <code>I</code>. The
pattern above has a very important drawback, and is that
<code>important_data</code> may end up not being defined. For example, if the file
<strong>my_data.dat</strong> doesn't exist, we will get another error:</p>
<pre><code class="language-bash">NameError: name 'important_data' is not defined
</code></pre>
<h2>The Finally Statement</h2>
<p>To prevent what we just saw in the previous section, we can add one more
block to the sequence: <code>finally</code>. This block is always going to be
executed, regardless of whether an exception was raised or not. For
example:</p>
<pre><code class="language-python">filename = 'my_data.dat'

try:
    file = open(filename)
    data = file.read()
    important_data = data[0]
except Exception as e:
    if isinstance(e, IndexError):
        print(e)
        data = 'Information'
        important_data = data[0]
    else:
        print('Unhandled exception')
finally:
    important_data = 'A'

print(important_data)
</code></pre>
<p>This is, in the end, a very silly example, because we are setting
<code>important_data</code> to a special value, but I hope you can see the use of
<code>finally</code>. If there is something that you must absolutely be sure that
is executed, you can include it in a finally statement.</p>
<p><code>finally</code> is very useful to be sure that you are closing a connection,
the communication with a device, closing a file, etc. Generally
speaking, releasing the resources. Finally has a very interesting
behavior, because it is not executed always at the same moment. Let's
see the following code:</p>
<pre><code class="language-python">filename = 'my_data.dat'

try:
    print('In the try block')
    file = open(filename)
    data = file.read()
    important_data = data[0]
except FileNotFoundError:
    print('File not found, creating one')
    file = open(filename, 'w')
finally:
    print('Finally, closing the file')
    file.close()
    important_data = 'A'

print(important_data)
</code></pre>
<p>First, run the code when the file <strong>my_data.dat</strong> doesn't exist. You
should see the following output:</p>
<pre><code class="language-bash">In the try block
File not found, creating one
Finally, closing the file
</code></pre>
<p>So, you see you went from the <code>try</code> to the <code>except</code> to the <code>finally</code>. If
you run the code again, the file will exist, and therefore the output
will be completely different:</p>
<pre><code class="language-bash">In the try block
Finally, closing the file
Traceback (most recent call last):
  File &quot;JJ_exceptions.py&quot;, line 7, in &lt;module&gt;
    important_data = data[0]
IndexError: string index out of range
</code></pre>
<p>What you can see here is that when an unhandled exception is raised, the
first block to be executed is the <code>finally</code>. You close the file
immediately. And then, the error is re-raised. This is very handy
because it prevents any kind of conflict with downstream code. You open,
you close the file and then the rest of the program has to deal with the
problem of the <code>IndexError</code>. If you want to try a program without
exceptions, just write something into <strong>my_data.dat</strong> and you will see
the output.</p>
<h2>The else Block</h2>
<p>There is only one more block to discuss in the exception handling
pattern, the <code>else</code> block. The core idea of this block is that it gets
executed if there were no exceptions within the <code>try</code> block. Is very
easy to understand how it works, you could, for example, do the
following:</p>
<pre><code class="language-python">filename = 'my_data.dat'

try:
    file = open(filename)
except FileNotFoundError:
    print('File not found, creating one')
    file = open(filename, 'w')
else:
    data = file.read()
    important_data = data[0]
</code></pre>
<p>The most difficult part of the else block is understanding its
usefulness. In principle, the code that we have included in the <code>else</code>
block could have also been placed right after opening the file, as we
have done earlier. However, we can use the <code>else</code> block to prevent
catching exceptions that do not belong to the <code>try</code>. It is a bit
far-fetched examples, but imagine that you need to read a filename from
a file and open it. The code would look like this:</p>
<pre><code class="language-python">try:
    file = open(filename)
    new_filename = file.readline()
except FileNotFoundError:
    print('File not found, creating one')
    file = open(filename, 'w')
else:
    new_file = open(new_filename)
    data = new_file.read()
</code></pre>
<p>Since we are opening two files, it may very well be that the problem is
that the second file doesn't exist. If we would put this code into the
<code>try</code> block, we would end up triggering the <code>except</code> for the second file
even if we didn't mean to. At first, it is not obvious the true use of
the <code>else</code> block, but it can be very useful and therefore it is
important that you are aware that it exists.</p>
<p>Of course, it is possible to combine everything that you have learned so
far:</p>
<pre><code class="language-python">try:
    file = open(filename)
    new_filename = file.readline()
except FileNotFoundError:
    print('File not found, creating one')
    file = open(filename, 'w')
else:
    new_file = open(new_filename)
    data = new_file.read()
finally:
    file.close()
</code></pre>
<p>You are very encouraged to play around and try to find different usages
for each block. If you have worked enough with Python, probably you
encounter plenty of exceptions that forced you to re-run your script
from the beginning. Now you know that there may be workarounds. A great
resource, as almost always, is the <a href="https://docs.python.org/3/tutorial/errors.html">Python Documentation on
Exceptions</a>.</p>
<p>Things are not over yet, there are many more things that can be done
with exceptions.</p>
<h2>The Traceback</h2>
<p>As you have probably seen already, when there is an exception, a lot of
information is printed to the screen. For example, if you try to open a
not existing file you get:</p>
<pre><code class="language-bash">Traceback (most recent call last):
  File &quot;P_traceback.py&quot;, line 13, in &lt;module&gt;
    file = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'my_data.dat'
</code></pre>
<p>Interpreting the message may take a bit of practice, but for simple
cases it is clear. First, it tells you that you are seeing a traceback,
in simple words the history of things that lead to the exception. I will
cover more on this on a separate post. However, you can clearly see the
file that generated the problem and the line. If you open the file and
go to that line, you will see that it is exactly the one that says
<code>file = open(filename)</code>. Finally, you see the exception.</p>
<p>This last message is the one we were printing to screen, but we were
neglecting the traceback that would allow us to find the real source of
the exception and act accordingly. Fortunately, Python allows us to
access the traceback very easily. Slightly modifying the example of
opening a file, we would have:</p>
<pre><code class="language-python">import traceback

filename = 'my_data.dat'

try:
    file = open(filename)
    data = file.read()
except FileNotFoundError:
    traceback.print_exc()
</code></pre>
<p>If you run the code again, you will see printed to screen the same
information than before. The main difference is that your program didn't
crash, because you were handling the exception. Working with tracebacks
is very handy for debugging. The examples that you have seen here are
very simple, but when you have a very nested code, i.e., one function
calls another that creates an object, that runs a method, etc. it is
very important to pay attention to the traceback in order to know what
triggered the exception.</p>
<h2>Raising Custom Exceptions</h2>
<p>When you are developing your own packages, it is often useful to define
some common exceptions. This gives a great deal of flexibility because
it allows other developers to handle those exceptions as they find
appropriate. Let's see an example. Imagine that you want to write a
function that calculates the average between two numbers, but you want
both numbers to be positive. This is the same example that we have seen
when working with
<a href="https://pythonforthelab.com/blog/how-to-use-decorators-part-2">decorators</a>. We start by
defining the function:</p>
<pre><code class="language-python">def average(x, y):
    return (x + y)/2
</code></pre>
<p>And now we want to raise an <code>Exception</code> if either input is negative. We
can do the following:</p>
<pre><code class="language-python">def average(x, y):
    if x&lt;=0 or y&lt;=0:
        raise Exception('Both x and y should be positive')
    return (x + y)/2
</code></pre>
<p>If you try it yourself with a negative input, you will see the following
printed:</p>
<pre><code class="language-bash">Exception: Both x and y should be positive
</code></pre>
<p>Which is great, it even points to the line number with the issue, etc.
However, if you are building a module and you expect others to use it,
it would be much better to define a custom Exception, that can be
explicitly caught. It is as easy as this:</p>
<pre><code class="language-python">class NonPositiveError(Exception):
    pass

def average(x, y):
    if x &lt;= 0 or y &lt;= 0:
        raise NonPositiveError('Both x and y should be positive')
    return (x + y) / 2
</code></pre>
<p>An exception is a class, and therefore it should inherit from the
general <code>Exception</code> class. We don't really need to customize anything at
this stage, we just type <code>pass</code> in the body of the class. If we run the
code above with a negative value, we will get:</p>
<pre><code class="language-bash">NonPositiveError: Both x and y should be positive
</code></pre>
<p>If you want to catch that exception in downstream code, you will do it
as always. The only difference is that custom exceptions are not
available by default and you should import them. For example, you would
do the following:</p>
<pre><code class="language-python">from exceptions import NonPositiveError
from tools import average

try:
    avg = average(1, -2)
except NonPositiveError:
    avg = 0
</code></pre>
<p>If you have worked long enough with packages, probably you have already
encountered a lot of different exceptions. They are a great tool to let
the user know exactly what was wrong and act accordingly. Sometimes we
can be prepared for some exceptions and is very appreciated when custom
ones are included into the package and not just a generic one that
forces us to catch any exception, even if it is something that we were
not actually expecting.</p>
<h2>Best Practices for Custom Exceptions</h2>
<p>When you are developing a package, it is very handy to define exceptions
that are exclusive to it. This makes it much easier to handle different
behaviors and gives developers a very efficient way to filter whether
the problems are within your package or with something else. Imagine,
for instance, that you are working with a complex package, and you want
to write to a file every time an exception from that specific package
appears.</p>
<p>This is very easy to achieve if all the exceptions inherit from the same
base class. The code below is a bit longer, but it is built on top of
all the examples above, so it should be easy to follow:</p>
<pre><code class="language-python">class MyException(BaseException):
    pass

class NonPositiveIntegerError(MyException):
    pass

class TooBigIntegerError(MyException):
    pass

def average(x, y):
    if x&lt;=0 or y&lt;=0:
        raise NonPositiveIntegerError('Either x or y is not positive')

    if x&gt;10 or y&gt;10:
        raise TooBigIntegerError('Either x or y is too large')
    return (x+y)/2

try:
    average(1, -1)
except MyException as e:
    print(e)

try:
    average(11, 1)
except MyException as e:
    print(e)

try:
    average('a', 'b')
except MyException as e:
    print(e)

print('Done')
</code></pre>
<p>We first define an exception called <code>MyException</code>, which is going to be
our base exception. We then define two errors, <code>NonPositiveIntegerError</code>
and <code>TooBigIntegerError</code> which inherit from <code>MyException</code>. We define the
function <code>average</code> again but this time we raise two different
exceptions. If one of the numbers is negative or larger than 10.</p>
<p>When you see the different use cases below, you will notice that in the
<code>try/except</code> block, we are always catching <code>MyException</code>, but not one of
the specific errors. In the first two examples, when passing <code>-1</code> and
<code>11</code> as arguments, we successfully print to screen the error message,
and the program keeps running. However, when we try to calculate the
average between two letters, the <code>Exception</code> is going to be of a
different nature, and is not going to be caught by the <code>Except</code>. You
should see the following on your screen:</p>
<pre><code class="language-bash">TypeError: '&lt;=' not supported between instances of 'str' and 'int'
</code></pre>
<h2>Adding Arguments to Exceptions</h2>
<p>Sometimes it is handy to add arguments to exceptions in order to give a
better context to users. With the example of the average, let's first
define a more complex exception:</p>
<pre><code class="language-python">class MyException(BaseException):
    pass

class NonPositiveIntegerError(MyException):
    def __init__(self, x, y):
        super(NonPositiveIntegerError, self).__init__()
        if x&lt;=0 and y&lt;=0:
            self.msg = 'Both x and y are negative: x={}, y={}'.format(x, y)
        elif x&lt;=0:
            self.msg = 'Only x is negative: x={}'.format(x)
        elif y&lt;=0:
            self.msg = 'Only y is negative: y={}'.format(y)

    def __str__(self):
        return self.msg


def average(x, y):
    if x&lt;=0 or y&lt;=0:
        raise NonPositiveIntegerError(x, y)
    return (x+y)/2

try:
    average(1, -1)
except MyException as e:
    print(e)
</code></pre>
<p>What you can see is that the exception takes two arguments, <code>x</code> and <code>y</code>
and it generates a message based on them. They can be both negative or
only one of them is negative. It doesn't only give you that information,
but it actually displays the value that gave problems. This is very
handy to understand what went wrong exactly. The most important part is
at the end of the class: the <code>__str__</code> method. This method is
responsible for what appears on the screen when you do <code>print(e)</code> in the
<code>except</code> block. In this case, we are just returning the message
generated within the <code>__init__</code>, but many developers choose to generate
the message in this method, based on the parameters passed at the
beginning.</p>
<h2>Conclusions</h2>
<p>Exceptions are something nobody wants to see but they are virtually
unavoidable. Maybe you try to read a file that doesn't exist, the user
of your code has chosen invalid values, the matrix you are analyzing has
different dimensions than expected, etc. Handling exceptions is a
sensitive topic because it can lead to even more problems downstream. An
Exception is a clear message that there is something wrong going on and
if you don't fix it properly, it is going to become even worse.</p>
<p>Handling exceptions can help you to avoid having inconsistent data, not
closing resources such as devices, connections or files, etc. However,
not handling exceptions correctly can lead to even more problems later
on. The <code>try/except</code> block is very handy when you know what kind of
exceptions can appear and you know how to handle them. Imagine you are
performing several steps of a complex operation, like writing to a
database. If an error happens, you can revert all the changes and avoid
inconsistencies.</p>
<p>As with almost any other Python topic, the best way to learn is to look
closely at other's code and judge by yourself. Not all packages define
their own exceptions, nor handle them in the same way. If you are
looking for inspiration, you can see the <a href="https://github.com/hgrecco/pint/blob/master/pint/errors.py">errors of
Pint</a>, a
relatively small package, or the <a href="https://github.com/django/django/blob/master/django/core/exceptions.py">exceptions of
Django</a>,
a much more complex package.</p>
<p>Photo by <a href="https://unsplash.com/photos/5E5N49RWtbA?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Cody
Davis</a>
on Unsplash</p>
        </main>
      </div>
      <div class="flex border-t text-lg px-4 pt-6 lg:pt-12 lg:mb-12">
        <div
            class="before:inset-y-1/2 before:inset-x-1 before:content-article before:h-6 before:w-6 before:inline-block before:align-middle"></div>
        <div class="pl-8 text-gray-600 font-light">Article written by Aquiles Carattino</div>
      </div>

      <div class="pt-4 pb-6 md:px-4 border-t border-gray-200 justify-center">
        <div class="bg-gray-300 font-serif text-2xl md:text-4xl text-center md:p-6 p-2">Join our newsletter!</div>
        <div class="py-4">If you liked the content, sign up to never miss an update.
        </div>
        <div id="mc_embed_signup" class="">
          <form
              action="https://pythonforthelab.us21.list-manage.com/subscribe/post?u=f0d9bfa6188cdcc67890a07f6&amp;id=8a0ca536e8&amp;f_id=00dfebe6f0"
              method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
              class="validate my-3 md:flex md:max-w-lg"
              target="_self" novalidate="">
            <div class="field-wp">
              <input type="email" name="EMAIL" placeholder="Your E-Mail" id="mce-EMAIL" required=""
                     value=""
                     class="required email bg-gray-100 ring-red-500 p-4 w-full md:max-w-2/3">
            </div>
            <div id="mce-responses" class="clear foot">
              <div class="response" id="mce-error-response" style="display: none;"></div>
              <div class="response" id="mce-success-response" style="display: none;"></div>
            </div>
            <div style="position: absolute; left: -5000px;" aria-hidden="true">
              /* real people should not fill this in and expect good things - do not remove this or risk
              form
              bot
              signups */
              <input type="text" name="b_f0d9bfa6188cdcc67890a07f6_8a0ca536e8" tabindex="-1" value="">
            </div>
            <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"
                   class="bg-emerald-500 hover:scale-105 w-full focus:bg-emerald-300 text-white p-4 mt-2 md:ml-4 md:mt-0 md:w-40">
          </form>
        </div>
      </div>

      <div class="px-2 lg:text-center lg:mt-8">
        <h4 class="text-2xl leading-tight lg:mx-auto lg:text-4xl">Share your thoughts with us!</h4>
        <div class="comments">
          <!-- Comment -->
          <script src="https://utteranc.es/client.js"
                  repo="PFTL/pftl_discussions"
                  issue-term="pathname"
                  label="Comment"
                  theme="github-light"
                  crossorigin="anonymous"
                  async>
          </script>
        </div>
      </div>
    </div>
    <div id="col-right" class="lg:w-72">
      <div class="bg-gray-300 place-items-center mt-3 p-6">
        <h3 class="font-serif text-2xl text-center mb-2 font-semibold mx-auto lg:text-xl">Support Us</h3>
        <p class="font-serif lg:text-sm leading-tight mb-2">If you like the content of this website, consider buying a
          copy of
          the book
          <strong>Python For The
            Lab</strong></p>
        <a href="https://pythonforthelab.com/books">
          <button class="bg-emerald-500 hover:scale-105 focus:bg-emerald-300 text-white p-4 mt-2 w-full md:max-w-2/3">
            Check out the books
          </button>
        </a>
      </div>

      <div class="mt-3 border border-gray-400  place-items-center">
          <h3 class="bg-gray-300 font-serif text-2xl lg:text-xl lg:font-bold text-center py-4">Latest Articles</h3>
          <ul class="mt-4">
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/instructions-to-build-the-python-for-the-lab-daq/" class="font-lg leading-tight hover:font-bold">
                  <div>Instructions to build the Python for the Lab DAQ.</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2021-03-27</div>
                </a>
              </li>
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/using-slots-in-python-limit-dynamic-attribute-creation-and-improve-speed" class="font-lg leading-tight hover:font-bold">
                  <div>Using slots in Python: limit dynamic attribute creation and improve speed</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2021-03-21</div>
                </a>
              </li>
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/getting-started-with-basler-cameras" class="font-lg leading-tight hover:font-bold">
                  <div>Acquiring images from Basler Cameras</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2021-02-27</div>
                </a>
              </li>
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/singletons-instantiate-objects-only-once" class="font-lg leading-tight hover:font-bold">
                  <div>Singletons: Instantiate objects only once</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2021-01-16</div>
                </a>
              </li>
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/differences-between-multiprocessing-windows-and-linux" class="font-lg leading-tight hover:font-bold">
                  <div>Differences of Multiprocessing on Windows and Linux</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2020-06-13</div>
                </a>
              </li>
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/python-tip-using-else-loops" class="font-lg leading-tight hover:font-bold">
                  <div>Python Tip: Using Else with Loops</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2020-05-25</div>
                </a>
              </li>
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/python-tip-ready-publish-matplotlib-figures" class="font-lg leading-tight hover:font-bold">
                  <div>Python Tip: Ready to Publish Matplotlib Figures</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2020-05-18</div>
                </a>
              </li>
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/data-descriptors-bringing-attributes-next-level" class="font-lg leading-tight hover:font-bold">
                  <div>Data Descriptors: Bringing Attributes to the Next level</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2020-05-16</div>
                </a>
              </li>
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/python-tips-using-sets" class="font-lg leading-tight hover:font-bold">
                  <div>Python Tips: Using Sets</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2020-05-11</div>
                </a>
              </li>
              <li class="mx-4 p-3 border-b border-b-gray-400">
                <a href="https://pythonforthelab.com/blog/generators-iterables-iterators-python-when-and-where" class="font-lg leading-tight hover:font-bold">
                  <div>Generators, Iterables, Iterators in Python: When and Where</div>
                  <div class="font-light text-gray-600 text-sm">
                    by Aquiles Carattino, 2020-04-10</div>
                </a>
              </li>
          </ul>
      </div>
    </div>
  </div>


<!-- Footer -->
<footer class="w-full bg-black text-white p-8">
  <div class="flex flex-row flex-wrap items-center justify-center gap-y-6 gap-x-12 text-center md:justify-between">
    <img src="https://pythonforthelab.com/theme/css/images/logo-red.svg" alt="logo-ct" class="w-20" />
    <ul class="flex flex-wrap items-center gap-y-2 gap-x-8">
      <li>
        <a
          href="https://pythonforthelab.com/about"
          class="block font-sans text-base font-normal leading-relaxed text-blue-gray-200 antialiased transition-colors hover:text-pink-500 focus:text-pink-500"
        >
          About Us
        </a>
      </li>
      <li>
        <a
          href="https://pythonforthelab.com/cookie-policy"
          class="block font-sans text-base font-normal leading-relaxed text-blue-gray-200 antialiased transition-colors hover:text-pink-500 focus:text-pink-500"
        >
          Cookie Policy
        </a>
      </li>
      <li>
        <a
          href="https://pythonforthelab.com/privacy-policy"
          class="block font-sans text-base font-normal leading-relaxed text-blue-gray-200 antialiased transition-colors hover:text-pink-500 focus:text-pink-500"
        >
          Privacy Policy
        </a>
      </li>
      <li>
        <a
          href="https://pythonforthelab.com/contact-us"
          class="block font-sans text-base font-normal leading-relaxed text-blue-gray-200 antialiased transition-colors hover:text-pink-500 focus:text-pink-500"
        >
          Contact Us
        </a>
      </li>
    </ul>
  </div>
  <hr class="my-8 border-blue-gray-50" />
  <p class="block text-center font-sans text-base font-normal leading-relaxed text-blue-gray-200 antialiased">
    © 2023 Python for the Lab
  </p>
</footer><script src="https://pythonforthelab.com/theme/js/prism.js"></script>
<script src="https://files.stork-search.net/releases/v1.5.0/stork.js"></script>
<script>
    stork.register("sitesearch", "https://pythonforthelab.com/search-index.st");
</script>

<script>
    $(document).ready(function () {
        responsive_menu = $('#menu');
        nav = $('nav');
        $('#menu-button').on('click', function (e) {
            e.preventDefault();
            if (responsive_menu.is(':hidden')) {
                responsive_menu.slideToggle();
                nav.addClass('bg-white');
                $("#site-logo").attr("src", "https://pythonforthelab.com/theme/css/images/logo-classic.svg");
                $('hamburger').slideToggle();
                $('#hamburger').attr('src', 'https://pythonforthelab.com/theme/css/images/cross.svg');
            } else {
                responsive_menu.slideToggle();
                nav.removeClass('bg-white');
                $("#site-logo").attr("src", "https://pythonforthelab.com/theme/css/images/logo-red.svg");
                $('#hamburger').attr('src', 'https://pythonforthelab.com/theme/css/images/hamburger.svg');
            }
        });
        position = $(window).height();
        $(window).scroll(function () {
            var currentScroll = $(window).scrollTop();
            if (currentScroll >= position) {
                $('#sticky_menu').addClass('lg:block');
            } else {
                $('#sticky_menu').removeClass('lg:block');
            }
        });
    });
</script></body>
</html>